team:
  f:
    discord:
      bot:
        command-prefix: '!'
        token:

spring:
  profiles:
    active: dev
  liquibase:
    enabled: true

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    com.github.shaart.team.f.discord.bot: TRACE