agile:
  bot:
    discord:
      command-prefix: '!'
      token:

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  liquibase:
    enabled: true

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    com.github.shaart.agile.bot: TRACE